# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83529addce2647d3a61bab6dc25cedf475f715636a27402d22fa01c85bfbc1454a1d6d3e2d9a14c9d5350e573b2e69b2b7f530021e4b6daac01372a43f4ac833
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  mailchimp_api_key: <%= ENV["PERSONAL_MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <% ENV["PERSONAL_MAILCHIMP_LIST_ID"] %>
  domain_name: example.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>

test:
  secret_key_base: 3e697029c6081938a843282be7af6926280333e2f1400af2df3344138451b3468aa1d5071824a238af87943e2a56b1de07f7aec899d0580b5e3a2115ef178ac2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  mailchimp_api_key: <%= ENV["PERSONAL_MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <% ENV["PERSONAL_MAILCHIMP_LIST_ID"] %>
  domain_name: example.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>
